package dev.cloudants.iulat.lib.components.context

object MODULE {
    var DASHBOARD = "DASHBOARD"
    val ADMINREPORTLIST  = "ADMINREPORTLIST"
    val USERLIST  = "USERLIST"
    var CHATDIRECT = "CHATDIRECT"
    var CHATLOBBY = "CHATLOBBY"
    var RESIDENCEDASHBOARD = "RESIDENCEDASHBOARD"
    var NOTIFICATIONLIST = "NOTIFICATIONLIST"
    var ACCOUNT = "ACCOUNT"
    var RESIDENCEREPORTLIST  = "RESIDENCEREPORTLIST"


    // RESIDENCE REPORT MODULE

    var GARBAGE_DISPOSAL = "GARBAGE_DISPOSAL"
    var PUBLIC_DISTURBANCE = "PUBLIC_DISTURBANCE"
    var ROBBERIES = "ROBBERIES"
    var BROKEN_STREETLIGHTS = "BROKEN_STREETLIGHTS"
    var VEHICLE_CRASH = "VEHICLE_CRASHES"
    var ROAD_REPAIR = "ROAD_REPAIR"
    var NO_WATER_SUPPLY = "NO_WATER_SUPPLY"
    var OTHERS = "OTHERS"
}